/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fenetre;


import java.awt.JobAttributes;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.OutputStream;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Depense;
import model.Utilisateur;
import util.Utilitaire;

/**
 *
 * @author yacine-pc
 */
public class Authentification extends javax.swing.JFrame {
DefaultTableModel model;

   
    public static String nomUtil;
     public static String nom;
      public static String prenom;
       public static String motPasse;
    /**
     * Creates new form Authentification
     */
    public Authentification() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelNomUtilisateur = new javax.swing.JLabel();
        jLabelMotDePasse = new javax.swing.JLabel();
        jTextFieldNomUtilisateur = new javax.swing.JTextField();
        jPasswordFieldMotDePasse = new javax.swing.JPasswordField();
        jButtonConnexion = new javax.swing.JButton();
        jButtonQuitter = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButtonInscription = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelNomUtilisateur.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabelNomUtilisateur.setText("Nom d'utilisateur :");
        jPanel1.add(jLabelNomUtilisateur, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 130, 29));

        jLabelMotDePasse.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabelMotDePasse.setText("Mot de passe :");
        jPanel1.add(jLabelMotDePasse, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 120, -1));
        jPanel1.add(jTextFieldNomUtilisateur, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 222, -1));
        jPanel1.add(jPasswordFieldMotDePasse, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 222, -1));

        jButtonConnexion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonConnexion.setText("Se connecter");
        jButtonConnexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConnexionActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonConnexion, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, -1, -1));

        jButtonQuitter.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonQuitter.setText("Quitter");
        jButtonQuitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonQuitterActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonQuitter, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel3.setText("vous n'avez pas un compte?");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 440, 201, -1));

        jButtonInscription.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonInscription.setText("s'inscrire");
        jButtonInscription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInscriptionActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonInscription, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 430, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/telecharger-jelly-bean-4-2.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 520, 360));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Starkode.Business.Expense.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 4, 630, 150));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonInscriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInscriptionActionPerformed
         // fermer cette fenetre 
        this.dispose();
        //ouvrir la fenetre de l'inscription
        Inscription ins = new Inscription();
        ins.setVisible(true);
       
    }//GEN-LAST:event_jButtonInscriptionActionPerformed

    private void jButtonQuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQuitterActionPerformed
        // TODO add your handling code here:
////        System.exit(0);
    }//GEN-LAST:event_jButtonQuitterActionPerformed

    private void jButtonConnexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConnexionActionPerformed

                                        
       
        boolean flag = true;

        File fichier = new File("utilisateurs.txt");
        BufferedReader br = null;
        FileReader fr = null;

        try {
            String password = String.valueOf(jPasswordFieldMotDePasse.getPassword());
            String nomUtilisateur = jTextFieldNomUtilisateur.getText();
//                if(nomUtilisateur.equals("")||password.equals("")){
//                    JOptionPane.showMessageDialog(null, "le nom d'utilisateur et le mot de passe sont obligatoires ","erreur saisie",JOptionPane.ERROR_MESSAGE);
//                }

            fr = new FileReader(fichier);

            br = new BufferedReader(fr);
            //split le fichier avec une virgule

            String line;
            //line=br.readLine();
            //fair le split pour pouvoir verifier 
            while ((line = br.readLine()) != null && flag) {

                String[] split = line.split(",");
                String line0 = split[0];
                String line1 = split[1];
                String line2 = split[2];
                String line3 = split[3];
                String line4 = split[4];
                String line5 = split[5];
                String line6 = split[6];
                String line7 = split[7];
                String line8 = split[8];
                String line9 = split[9];
                String line10 = split[10];
                String line11 = split[11];
                String line12 = split[12];
                String line13 = split[13];
                String line14 = split[14];
                String line15 = split[15];

                String nom = line1;
                String prenom = line3;
                String nomUtil = line5;
                String motPasse = line7;
                double budjet = Double.parseDouble(line9);
                double balance = Double.parseDouble(line11);
                double somme = Double.parseDouble(line13);
                String date = line15;

                // comparer le nom d'tuilisateur et le mot de passe tape par l'tilisateur avec les donnes du fichier
                if (line7.equals(password) && line5.equals(nomUtilisateur)) {//si tout est correct on ouvre la fenetre depenseAffichage
//               

                    // fermer cette fenetre
                    this.dispose();

                    //afficher la fentre des operations
                    DepenseAffichage dp = new DepenseAffichage();

                    dp.setVisible(true);
                    dp.jTextFieldNom.setText(nom);
                    dp.jTextFieldPrenom.setText(prenom);
                    dp.jTextFieldEtatConnexion.setText("connecte");

                    Utilisateur u = new Utilisateur(nomUtilisateur, motPasse, nom, prenom, date, budjet, balance, somme);

                    // fermer cette fenetre
         
                } else if (line7 != password && line5 != nomUtilisateur && !flag) {//sinon on lui demande de reecrir le nom d'utilisateur ou le mot de passe
                    JOptionPane.showMessageDialog(null, "Nom d'utilisateur ou mot de passe incorrect,veillez reessayer SVP", "erreurmot de passe", JOptionPane.ERROR_MESSAGE);

                }


            }

        } catch (FileNotFoundException ex) {
            Logger.getLogger(DepenseAffichage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(DepenseAffichage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "le nom d'utilisateur et le mot de passe sont obligatoires ", "erreur saisie", JOptionPane.ERROR_MESSAGE);
        }
        try {
            br.close();
            fr.close();
        } catch (IOException ex) {
            Logger.getLogger(DepenseAffichage.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jButtonConnexionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Authentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Authentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Authentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Authentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Authentification().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConnexion;
    private javax.swing.JButton jButtonInscription;
    private javax.swing.JButton jButtonQuitter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelMotDePasse;
    private javax.swing.JLabel jLabelNomUtilisateur;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JPasswordField jPasswordFieldMotDePasse;
    public static javax.swing.JTextField jTextFieldNomUtilisateur;
    // End of variables declaration//GEN-END:variables

}
