/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fenetre;


import java.io.BufferedInputStream;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.DataOutputStream;
import java.io.EOFException;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Calendar;
import java.util.Date;
import java.util.Iterator;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import model.Depense;
import model.RegistreDepense;
import model.Utilisateur;
import util.Utilitaire;

/**
 *
 * @author yacine-pc
 */
public class Inscription extends javax.swing.JFrame {
   
    /**
     * Creates new form Inscription
     */
    public Inscription() {
        
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelNom = new javax.swing.JLabel();
        jLabelPrenom = new javax.swing.JLabel();
        jLabelNomUtilisateur = new javax.swing.JLabel();
        jLabelMotDePasse = new javax.swing.JLabel();
        jLabelCondfirmationMotDePasse = new javax.swing.JLabel();
        jTextFieldNom = new javax.swing.JTextField();
        jTextFieldPrenom = new javax.swing.JTextField();
        jTextFieldNomUtilisateur = new javax.swing.JTextField();
        jPasswordFieldMotDePasse = new javax.swing.JPasswordField();
        jPasswordConfirmation = new javax.swing.JPasswordField();
        jButtonSinscrire = new javax.swing.JButton();
        jButtonAnnuler = new javax.swing.JButton();
        jButtonQuitter = new javax.swing.JButton();
        jButtonRetourPremierePage = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelNom.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabelNom.setText("Nom :");
        jPanel1.add(jLabelNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 114, 195, -1));

        jLabelPrenom.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabelPrenom.setText("Prenom :");
        jPanel1.add(jLabelPrenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 175, 195, -1));

        jLabelNomUtilisateur.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabelNomUtilisateur.setText("Nom d'utilisateur :");
        jPanel1.add(jLabelNomUtilisateur, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 232, 195, -1));

        jLabelMotDePasse.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabelMotDePasse.setText("Mot de passe :");
        jPanel1.add(jLabelMotDePasse, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 291, 195, -1));

        jLabelCondfirmationMotDePasse.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabelCondfirmationMotDePasse.setText("Confirmation mot de passe :");
        jPanel1.add(jLabelCondfirmationMotDePasse, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 346, -1, -1));
        jPanel1.add(jTextFieldNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 114, 183, -1));
        jPanel1.add(jTextFieldPrenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 175, 183, -1));
        jPanel1.add(jTextFieldNomUtilisateur, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 232, 183, -1));

        jPasswordFieldMotDePasse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldMotDePasseActionPerformed(evt);
            }
        });
        jPanel1.add(jPasswordFieldMotDePasse, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 291, 183, -1));
        jPanel1.add(jPasswordConfirmation, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 346, 183, -1));

        jButtonSinscrire.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonSinscrire.setText("s'inscrire");
        jButtonSinscrire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSinscrireActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSinscrire, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 411, -1, -1));

        jButtonAnnuler.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonAnnuler.setText("Annuler");
        jButtonAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnnulerActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAnnuler, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 411, -1, -1));

        jButtonQuitter.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonQuitter.setText("Quitter");
        jButtonQuitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonQuitterActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonQuitter, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 411, -1, -1));

        jButtonRetourPremierePage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back.png"))); // NOI18N
        jButtonRetourPremierePage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRetourPremierePageActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonRetourPremierePage, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 105, 92));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/telecharger-jelly-bean-4-2.jpg"))); // NOI18N
        jLabel6.setText("yacine");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -1, 640, 480));

        jTextField1.setText("jTextField1");
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, 130, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonQuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQuitterActionPerformed
       //quitter le system
       System.exit(0);
    }//GEN-LAST:event_jButtonQuitterActionPerformed

    private void jButtonRetourPremierePageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRetourPremierePageActionPerformed
    //fermer la fentre inscription
        this.dispose();
        //ouvrir la fenetre DepenseAffichage
     Authentification dep = new Authentification();
      dep.setVisible(true);
    }//GEN-LAST:event_jButtonRetourPremierePageActionPerformed

    private void jButtonSinscrireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSinscrireActionPerformed
           
//            ArrayList<Depense> list = new ArrayList<>();  
            String nom = jTextFieldNom.getText();
            String prenom = jTextFieldPrenom.getText();
            String nomUtilisateur = jTextFieldNomUtilisateur.getText();
           
            String motDePasse = String.valueOf(jPasswordFieldMotDePasse.getPassword());
            String confirmation = String.valueOf(jPasswordConfirmation.getPassword());
         //verifier si tout les champs sont bien saisies
        Utilitaire.verifierChapm(nom, prenom, nomUtilisateur, motDePasse, confirmation);
              //on verifie si le mot de passe se matche avec la confirmation pour valider le mot de passe
        if(!Utilitaire.isPasswordCorrect(motDePasse, confirmation)){
                //si le mot de passe n'egale pas la confirmation 
           JOptionPane.showMessageDialog(null, "mot de passe incorect,veillez reecrir le mot de passe SVP","erreur",JOptionPane.ERROR_MESSAGE);
            }//sdi le mot de passe est correct
        else if (Utilitaire.isPasswordCorrect(motDePasse, confirmation)){
                 
                //on va a l'etape suivante est de verifier le nom d'utilisateur s'il existe dans le fichier
                //utiliser la methode verifierNomUtilisateur elle retourne false si le nom n'existe pas dans le fichier
        if( ! Utilitaire.verifierNomUtilisateur(nomUtilisateur, "utilisateurs.txt")){// ici si le nom d'utilisateur existe
                  
        }else if (  Utilitaire.verifierNomUtilisateur(nomUtilisateur, "utilisateurs.txt")){//ici on procede a l'enregistreent vu que le nom d'utilisateur n'existe pas dans le fichier
          //recuperer l'heure d'aujourdhui pour la mettre par defaut dans l'attribut date de l'utilisateur   
        SimpleDateFormat dtf = new SimpleDateFormat("yyyy/MM/dd");
        Calendar calendar = Calendar.getInstance();
        Date dateObj = calendar.getTime();
        String formattedDate = dtf.format(dateObj);
        String date =  formattedDate; 
                       
          //creer l'utilisateur a partir des donnes qu'on a puis la balance , budget , somme vont etre a zero par defaut
          Utilisateur ut = new Utilisateur(nomUtilisateur, motDePasse, nom, prenom,date,0.0,0.0,0.0);
              //verifier si tous les champs sont saisis
            Utilitaire.verifierChapm(nom, prenom, nomUtilisateur, motDePasse, confirmation);
            //la methode qui enregistre le nouveau utuisateur dans le fichier
            //enregistrer dans un fichier notmal
            String msg = "enregistrement avec succe,veillez vous connecter pour utiliser l'application,merci!";
            Utilitaire.saveUser(ut,"utilisateurs.txt",msg);
            String fichierPersonnel = nomUtilisateur+".txt";
            Utilitaire.saveUser(ut, fichierPersonnel, msg);
            //vider tous les champs de la fentre apres bien s'enregistrer
           ViderLesChamps();
           
                   }
                
            
            }
       
                          
    }//GEN-LAST:event_jButtonSinscrireActionPerformed

    private void jPasswordFieldMotDePasseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldMotDePasseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldMotDePasseActionPerformed

    private void jButtonAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnnulerActionPerformed
     // vider tous les champs de la fenetres
     ViderLesChamps();;
    }//GEN-LAST:event_jButtonAnnulerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inscription().setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnnuler;
    private javax.swing.JButton jButtonQuitter;
    private javax.swing.JButton jButtonRetourPremierePage;
    private javax.swing.JButton jButtonSinscrire;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelCondfirmationMotDePasse;
    private javax.swing.JLabel jLabelMotDePasse;
    private javax.swing.JLabel jLabelNom;
    private javax.swing.JLabel jLabelNomUtilisateur;
    private javax.swing.JLabel jLabelPrenom;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordConfirmation;
    private javax.swing.JPasswordField jPasswordFieldMotDePasse;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextFieldNom;
    private javax.swing.JTextField jTextFieldNomUtilisateur;
    private javax.swing.JTextField jTextFieldPrenom;
    // End of variables declaration//GEN-END:variables

    private void ViderLesChamps() {
        jTextFieldNom.setText("");
        jTextFieldNomUtilisateur.setText("");
        jTextFieldPrenom.setText("");
        jPasswordFieldMotDePasse.setText("");
        jPasswordConfirmation.setText("");
        
    }

 //String nom, String prenom, String nomUtilisateur, String motDePasse, String confirmation)

    
  

}
